### ISSUE TITLE
Initial Browser Agent

### ISSUE THREAD

**Issue by nikmd23** [Glimpse/Glimpse.Client.Prototype#10]
The initial browser agent should be created to simply submit Navigation timing, Resource timing and User timing information.

In order for this to be completed, several pieces of infrastructure will need to be in place:

- The script tag injector must know the requestId to be able to add a `data-*` attribute.
- The browser agent must know the URL to post the data to.
- The resource that receives the data must be in working condition.
- There may need to be a JavaScript broker in place.

**Comment by avanderhoorn** [comment]
This is complete... source code currently lives int the server project with the server agent... need to be reworked in the future.
