### ISSUE TITLE
[HttpServer] Validate currently showed data 

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Client.Prototype#15]
Confirm that the General info is currently being highlighted appropriately.

**Comment by nikmd23** [comment]
Can you add a bit more context to this issue? I'm not sure what I'm supposed to be doing to complete this.

**Comment by avanderhoorn** [comment]
Are you happy with the "Http" data that we are showing the summary rows and in the details header (the blue section)? I created this just case their was something missing that you wanted, but I'm assuming its not. That being the case, just mark as completed.

**Comment by nikmd23** [comment]
I'm happy with the data as show in #30.

With that, I can close this issue.
