### ISSUE TITLE
[HttpServer] Display request/response headers

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Client.Prototype#16]
Update UI to render Request/Response headers in line with current Execution tab:
 - [x] Update execution tab to show headers
 - [x] Get feedback/review of final UI design
 - [ ] Add unit tests**

** Note we currently don't have unit tests for the UI. This point will need to reviewed depending on the state of the client unit tests.

**Design:**
It is expected that the Request Headers will be displayed at the top of the Execution Tab and Response Headers at the bottom. The section should have both a summary view and details view (as we need to be careful how much vertical space we take up). The keys of the headers should be highlighted/bolded, and the values parsed/trimmed/formatted as it makes sense.

**Comment by avanderhoorn** [comment]
Given that we are now not putting this into the Execution tab, we need to think about the design we want for the Request tab. @nikmd23 thoughts?

**Comment by nikmd23** [comment]
> We need to think about the design we want for the Request tab

This has been covered and can now be seen in #30

**Comment by avanderhoorn** [comment]
Completed with #30 with the exception of unit tests which aren't in scope atm.
