### ISSUE TITLE
[Middleware] Update UI to show basic activity

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Client.Prototype#19]
Update UI to render basic middleware data in line with current Execution tab:
 - [ ] Update execution tab to show basic Middleware data (i.e. name, order, duration, etc)
 - [ ] Get feedback/review of final UI design
 - [ ] Add unit tests**

** Note we currently don't have unit tests for the UI. This point will need to reviewed depending on the state of the client unit tests.

**Design:**
Currently the design has the header middleware showing up under the request headers and above the current Connect/MVC data, and the footer middleware showing up above the response headers and below the current Connect/MVC data. We expect for the data to be nested, to help enforce the ordering of middleware.

**Comment by nikmd23** [comment]
Here's a quick mockup of how middleware could be displayed. It's based on [a simple sample app from the Connect documentation](https://github.com/senchalabs/connect#connect).

```js
var connect = require('connect');
var http = require('http');

var app = connect();

// gzip/deflate outgoing responses
var compression = require('compression');
app.use(compression());

// store session state in browser cookie
var cookieSession = require('cookie-session');
app.use(cookieSession({
    keys: ['secret1', 'secret2']
}));

// parse urlencoded request bodies into req.body
var bodyParser = require('body-parser');
app.use(bodyParser.urlencoded());

// respond to all requests
app.use(function(req, res){
  res.end('Hello from Connect!\n');
});

//create node.js http server and listen on port
http.createServer(app).listen(3000);
```
![Middleware Mockup](https://cloud.githubusercontent.com/assets/199026/13442688/16fd3284-dfc3-11e5-9416-33ecf39cb7f9.png)

Of course, this could all 100% change when a designer comes on board, so just focus on the key features:

 1. Middleware Names/Identifiers
 2. Duration
 3. Configuration

**Comment by nebrius** [comment]
Small nit, but we may want to think about how we display anonymous functions. Named anonymous functions are pretty rare in the wild, and arrow functions will only make them more common since they can only be anonymous.

The current mockup makes them look like not naming them is a warning, or something to be fixed, and I have the suspicion that `fn.displayName` will confuse people.

**Comment by nikmd23** [comment]
Please note: This is not the real UI. That tip is just a placeholder example to convey  the idea that we'll guide the user into somehow annotating a more meaningful name, if they want it.

Figuring out how to display anonymous functions is one of the tasks key tasks we have to do.

**Comment by avanderhoorn** [comment]
Shifted conversation or more relevant repo.
