### ISSUE TITLE
[HttpClient] Create UI Design Mockup

### ISSUE THREAD

**Issue by nikmd23** [Glimpse/Glimpse.Client.Prototype#44]
The Http Services tab in Glimpse should look something like this:

![http services - eventually](https://cloud.githubusercontent.com/assets/199026/13826374/217c8912-eb85-11e5-9988-e1b89a9a8bee.png)

*(***Note***: This rough sketch is only provided to inspire. It's layout and design choices are not intended to be limited by what you see here.)*

This issue should be used to track the progress of the design and provide feedback to @chetsangnil

**Comment by chetsangnil** [comment]
Latest complete walk through pdf for "Web Services" tab

[Web Services V8_Complete Walk Through.pdf](https://github.com/Glimpse/Glimpse.Client.Prototype/files/205118/Web.Services.V8_Complete.Walk.Through.pdf)

Here're all the .png for the pdf. In case you need to use them for any reason later ;)

<img width="1109" alt="web services v8-1" src="https://cloud.githubusercontent.com/assets/7482923/14294266/ff8f8ade-fb24-11e5-8c3f-2ddec766e381.png">
<img width="1109" alt="web services v8-2" src="https://cloud.githubusercontent.com/assets/7482923/14294268/ff91a58a-fb24-11e5-90c9-79b6f8a7881b.png">
<img width="1109" alt="web services v8-3" src="https://cloud.githubusercontent.com/assets/7482923/14294265/ff8f1c84-fb24-11e5-8acd-d112c19fc044.png">
<img width="1109" alt="web services v8-4" src="https://cloud.githubusercontent.com/assets/7482923/14294269/ff940fb4-fb24-11e5-8bf2-df6b53978cf9.png">
<img width="1109" alt="web services v8-5" src="https://cloud.githubusercontent.com/assets/7482923/14294267/ff90020c-fb24-11e5-84d3-9aaef0b91382.png">
<img width="1109" alt="web services v8-6" src="https://cloud.githubusercontent.com/assets/7482923/14294264/ff8e85e4-fb24-11e5-9a50-f7d53201b908.png">
<img width="1109" alt="web services v8-7" src="https://cloud.githubusercontent.com/assets/7482923/14294270/ff9c7e6a-fb24-11e5-9d17-2c8117e1dfbc.png">
<img width="1109" alt="web services v8-8" src="https://cloud.githubusercontent.com/assets/7482923/14294274/ffa33cdc-fb24-11e5-800f-1a2d9fd5f8eb.png">
<img width="1109" alt="web services v8-9" src="https://cloud.githubusercontent.com/assets/7482923/14294271/ff9e13f6-fb24-11e5-9d31-5c81757e68fc.png">
<img width="1109" alt="web services v8-10" src="https://cloud.githubusercontent.com/assets/7482923/14294273/ffa30096-fb24-11e5-9c29-f1dd670b41ef.png">
<img width="1109" alt="web services v8-11" src="https://cloud.githubusercontent.com/assets/7482923/14294272/ffa0f3b4-fb24-11e5-829f-a9be53035ce3.png">
<img width="1109" alt="web services v8-12" src="https://cloud.githubusercontent.com/assets/7482923/14294275/ffa6f458-fb24-11e5-90aa-c30ba6ed0cea.png">
<img width="1109" alt="web services v8-13" src="https://cloud.githubusercontent.com/assets/7482923/14294276/ffab127c-fb24-11e5-9241-fdd5abf67638.png">
<img width="1109" alt="web services v8-14" src="https://cloud.githubusercontent.com/assets/7482923/14294277/ffaf581e-fb24-11e5-9bfb-c96e3abac58e.png">
<img width="1109" alt="web services v8-15" src="https://cloud.githubusercontent.com/assets/7482923/14294278/ffafb958-fb24-11e5-8b09-b2b2963f10e6.png">
<img width="1109" alt="web services v8-16" src="https://cloud.githubusercontent.com/assets/7482923/14294279/ffb64d5e-fb24-11e5-859c-1764e88c9203.png">

**Comment by chetsangnil** [comment]
Minor tweak on color on the text here! Thank you!

<img width="1109" alt="web services v11-1" src="https://cloud.githubusercontent.com/assets/7482923/14368032/11221c1a-fcd0-11e5-94ee-d3b4db7d972f.png">

**Comment by avanderhoorn** [comment]
This was completed with #67
